version: '3.8'
services:
  coin-vault-microservice-portfolio:
    image: robfontys/coin-vault-microservice-portfolio:latest
    networks:
      - CoinVault-network
    ports:
      - 3001:3000

  coin-vault-microservice-trade:
    image: robfontys/coin-vault-microservice-trade:latest
    networks:
      - CoinVault-network
    ports:
      - 3002:3000

networks:
  CoinVault-network:     